/**
 * Purpose: dev-time canonical-pipeline step 3 (spec 025) — convert the verified extraction
 * outputs (kebiao-fine.json, mdn-fine.json) and the Wikidata-enriched concept list
 * (concepts.json) into the checked-in generated TypeScript data the app imports: fine-grained
 * profile items (grouped under their （ｎ） sub-headings) and the canonical concept inventory.
 * Usage: node scripts/canonical/gen-data.mjs <kebiao-fine.json> <mdn-fine.json> <concepts.json>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { normalize } from "./shared.mjs";

const [, , kebiaoPath, mdnPath, conceptsPath] = process.argv;
if (!kebiaoPath || !mdnPath || !conceptsPath) {
  console.error("usage: node gen-data.mjs <kebiao-fine.json> <mdn-fine.json> <concepts.json>");
  process.exit(1);
}

const kebiao = JSON.parse(readFileSync(kebiaoPath, "utf8"));
const mdn = JSON.parse(readFileSync(mdnPath, "utf8"));
const { concepts } = JSON.parse(readFileSync(conceptsPath, "utf8"));
const conceptIdByLabel = new Map(concepts.map((concept) => [normalize(concept.label), concept.id]));
for (const concept of concepts)
  concept.aliases = Array.isArray(concept.aliases) ? concept.aliases : [];
for (const concept of concepts) {
  for (const alias of concept.aliases) {
    if (!conceptIdByLabel.has(normalize(alias))) conceptIdByLabel.set(normalize(alias), concept.id);
  }
}

function clip(text, max) {
  return text.length > max ? `${text.slice(0, max)}…` : text;
}

/** Builds ProfileItemDefinition literals for one extraction file. Group items (（ｎ）级小标题)
 * become intermediate nodes; concepts hang under their group, or the unit when ungrouped. */
function buildItems(items, sourceRefOf) {
  const output = [];
  const groupKeyByLabel = new Map();
  const seenLeafByUnit = new Set();
  let groupSeq = 0;
  let leafSeq = 0;
  for (const item of items) {
    const unitKey = item.unitKey;
    const stripped = item.parent === null ? null : item.parent.replace(/^（[^）]*）\s*/u, "");
    if (
      item.parent === null &&
      items.some(
        (other) =>
          other.parent !== null &&
          normalize(other.parent.replace(/^（[^）]*）\s*/u, "")) === normalize(item.label) &&
          other.unitKey === unitKey,
      )
    ) {
      continue; // this heading materializes as a group below
    }
    let parentKey = unitKey;
    if (stripped !== null) {
      const groupId = `${unitKey}|${normalize(stripped)}`;
      if (!groupKeyByLabel.has(groupId)) {
        groupSeq += 1;
        const key = `${unitKey}-g${groupSeq}`;
        groupKeyByLabel.set(groupId, key);
        output.push({
          key,
          parentKey: unitKey,
          label: clip(stripped, 60),
          aliases: [],
          sourceRef: sourceRefOf(item, true),
          conceptId: null,
        });
      }
      parentKey = groupKeyByLabel.get(groupId);
    }
    const leafDedup = `${unitKey}|${normalize(item.label)}`;
    if (seenLeafByUnit.has(leafDedup)) continue;
    seenLeafByUnit.add(leafDedup);
    leafSeq += 1;
    output.push({
      key: `${unitKey}-f${leafSeq}`,
      parentKey,
      label: clip(item.label, 60),
      aliases: [],
      sourceRef: sourceRefOf(item, false),
      conceptId: conceptIdByLabel.get(normalize(item.label)) ?? `c:${normalize(item.label)}`,
    });
  }
  return output;
}

const mathItems = buildItems(kebiao.items, (item, isGroup) =>
  clip(
    isGroup
      ? `《普通高中数学课程标准（2017年版2020年修订）》内容要求（逐字校验通过）`
      : `课标内容要求原文：「${item.quote}」（逐字校验通过）`,
    290,
  ),
);
const mdnItems = buildItems(mdn.items, (item, isGroup) =>
  clip(
    isGroup
      ? `MDN Curriculum learning outcomes（逐字校验通过）`
      : `${item.sourceUrl} · 原文：「${item.quote}」（逐字校验通过）`,
    290,
  ),
);

/** Every fine leaf's concept must exist in the inventory — add slug concepts for labels the
 * Wikidata pass had no confident QID for. */
const conceptRecords = [...concepts];
const knownIds = new Set(conceptRecords.map((concept) => concept.id));
for (const item of [...mathItems, ...mdnItems]) {
  if (item.conceptId !== null && !knownIds.has(item.conceptId)) {
    knownIds.add(item.conceptId);
    conceptRecords.push({
      id: item.conceptId,
      label: item.label,
      aliases: [],
      sourceRef: "无置信 QID——以清单来源为准",
    });
  }
}

const header = (purpose) => `/**
 * Purpose: GENERATED by scripts/canonical/gen-data.mjs (spec 025) — do not edit by hand;
 * re-run the canonical pipeline instead. ${purpose}
 */
`;

writeFileSync(
  new URL("../../apps/desktop/src/data/generated/canonicalConcepts.ts", import.meta.url),
  `${header("Main exports: CANONICAL_CONCEPTS.")}export interface CanonicalConceptData {
  id: string;
  label: string;
  aliases: string[];
  sourceRef: string;
}

export const CANONICAL_CONCEPTS: CanonicalConceptData[] = ${JSON.stringify(conceptRecords, null, 2)};
`,
);

writeFileSync(
  new URL("../../apps/desktop/src/data/generated/fineItems.ts", import.meta.url),
  `${header("Main exports: MATH_FINE_ITEMS, MDN_FINE_ITEMS.")}import type { ProfileItemDefinition } from "@breadcrumb/feature-compare";

export const MATH_FINE_ITEMS: ProfileItemDefinition[] = ${JSON.stringify(mathItems, null, 2)};

export const MDN_FINE_ITEMS: ProfileItemDefinition[] = ${JSON.stringify(mdnItems, null, 2)};
`,
);
console.log(`math=${mathItems.length} mdn=${mdnItems.length} concepts=${conceptRecords.length}`);
