/** The demo learner in 简体中文 — the source text every other language was written from. */
import type { DemoText } from "./demoText";

export const DEMO_TEXT_ZH_CN: DemoText = {
  concepts: {
    "astro-root": ["天文观测基础", "观测方法与测量工具的框架。"],
    "stellar-spectra": ["恒星光谱分类", "按谱线特征给恒星分类。"],
    "js-root": ["JavaScript核心机制", "运行时调度代码执行的底层规则。"],
    parallax: ["视差测距法", "用地球公转基线测算恒星距离。"],
    closures: ["闭包与作用域链", "函数保留其定义时的变量环境。"],
    transits: ["系外行星凌日法", "行星掠过恒星前方造成的掉光。"],
    "event-loop": ["事件循环与微任务", "协调同步代码与微任务的执行顺序。"],
    "promise-chains": ["Promise链式调用", "用 then 串联多个异步步骤。"],
    "event-horizon": ["黑洞事件视界", "光也无法逃逸的边界。"],
    "async-await": ["async/await语法", "用同步写法表达异步流程的语法糖。"],
    "tidal-locking": ["潮汐锁定", "自转周期与公转周期相等的现象。"],
    "prototype-chain": ["原型链继承", "对象沿原型链向上查找属性。"],
    "kepler-laws": ["开普勒定律", "行星轨道形状与公转周期的关系。"],
    destructuring: ["解构赋值", "按结构从数组或对象里取值。"],
    "magnitude-scale": ["星等标尺", "衡量天体亮度的对数标尺。"],
    "array-higher-order": ["数组高阶函数", "接受函数作为参数的数组方法。"],
    "gravitational-lensing": ["引力透镜", "大质量天体弯曲背景光路径的现象。"],
    "debounce-throttle": ["防抖与节流", "限制高频事件触发频率的两种手法。"],
    "white-dwarf": ["白矮星", "恒星耗尽核燃料后的致密残骸。"],
    "es-modules": ["模块化与ES Modules", "用 import/export 组织依赖关系。"],
    "neutron-star": ["中子星", "超新星爆发后留下的致密星体。"],
    "recursion-call-stack": ["递归与调用栈", "函数调用自身,依赖调用栈保存状态。"],
    cmb: ["宇宙微波背景辐射", "大爆炸残留的均匀微波辐射。"],
    "regex-capture-groups": ["正则表达式捕获组", "用括号在正则里截取匹配子串。"],
    "array-map": ["map映射", "把数组逐项变换成等长的新数组。"],
    "array-filter": ["filter筛选", "按条件挑出数组中的一部分。"],
    "array-reduce": ["reduce归约", "把整个数组折叠成一个值。"],
    "method-chaining": ["链式调用", "map/filter 连着写,数据像流水线一样过。"],
    "sparse-arrays": ["稀疏数组的坑", "空位不会被 map 访问,结果常出乎意料。"],
    "predicate-functions": ["谓词函数", "返回真假的判断函数,是 filter 的心脏。"],
    truthiness: ["真值判定", "JS 里哪些值算「真」,哪些算「假」。"],
    "accumulator-pattern": ["累加器模式", "用一个不断更新的累加器收集结果。"],
    "reduce-initial-value": ["初始值的选择", "reduce 的第二个参数决定第一轮怎么开始。"],
    "map-via-reduce": ["reduce实现map", "用 reduce 写出 map,理解归约的表达力。"],
    "group-by": ["分组统计groupBy", "按键把元素分进不同的组。"],
    "object-accumulator": ["对象累加", "累加器是对象时的合并写法。"],
    "lazy-evaluation-tradeoff": ["惰性求值的取舍", "链式好读,但每步都产生中间数组。"],
    "composing-predicates": ["组合谓词", "用与、或把多个判断拼成一个。"],
    "map-or-object": ["Map还是对象", "分组容器选 Map 还是普通对象。"],
  },
  titles: {
    astro: "【演示】天文漫游",
    js: "【演示】JS 温故知新",
    teach: "回讲·闭包与作用域链",
    vocab: "【演示】词汇复盘",
  },
  astroMessages: [
    "早上看到一张星系团的照片,光好像被弯曲了,这是什么现象",
    "这是引力透镜:大质量天体的引力会弯曲背后光源发出的光线路径,让背景星系的像发生扭曲或多重成像。",
    "之前聊过的恒星光谱分类,能不能跟这个现象放一起理解",
    "可以:光谱分类看的是恒星本身发出光的成分和温度,引力透镜看的是光路径被路过质量弯曲,两者是独立的物理过程,但都要用光谱和成像数据分析。",
    "那开普勒定律和视差测距法呢,今天复习一下天文观测基础的框架",
    "开普勒定律描述行星轨道形状与周期的关系,视差测距法用地球公转基线测恒星距离,两者都是天文观测基础里的定位工具。",
  ],
  jsMessages: [
    "写代码时又碰到面试常问的事件循环,想巩固一下JavaScript核心机制这条线",
    "JavaScript核心机制这条线里,事件循环负责协调同步代码、微任务和宏任务的执行顺序,是理解异步行为的基础。",
    "闭包和这个有关系吗",
    "闭包本身和事件循环是两回事,但闭包常用来在异步回调里保存状态,所以两者经常一起出现在代码里。",
  ],
  teachMessages: [
    "我来讲讲闭包:函数记住了它定义时所在的作用域,即使外层函数已经执行完,内部函数依然能访问那些变量,常用来做数据私有化,比如计数器场景。",
    "解释准确,抓住了定义时作用域被保留这个核心机制,私有化计数器的例子也用对了。",
  ],
  vocabMessages: [
    "这周单词量涨得挺快,有没有什么感觉",
    "从最近的猜词记录看,不少词的正确率提升了,继续保持每天接触的节奏就够。",
    "有些词还是会看到就愣一下",
    "愣一下说明还在巩固阶段,不是没学会,等间隔拉长后自然会更快反应过来。",
  ],
  wordContexts: [
    "对话里提到了「{word}」这个说法。",
    "这段内容中出现了「{word}」。",
    "复习卡片上写着「{word}」。",
  ],
};
