"""Purpose: the stylesheet half of the font slicer — one @font-face per slice, each with
the unicode-range that says which characters it is worth fetching for.
Main exports: write_css.
"""

from __future__ import annotations

from pathlib import Path

FAMILY = "LXGW WenKai"

HEADER = f"""/* {FAMILY}, by LXGW — https://github.com/lxgw/LxgwWenKai
 * SIL Open Font License 1.1; the full text is in ../OFL.txt, which ships with the app.
 * The licence's ADDITIONAL PERMISSION covers exactly this: the reserved name may stay on a
 * version subsetted or converted to WOFF2 for web delivery, as long as it is not offered as
 * an installable desktop font. These slices are not.
 *
 * GENERATED by scripts/fonts/split-wenkai.py — do not edit by hand.
 */
"""


def unicode_range(codepoints: list[int]) -> str:
    """The CSS descriptor, with runs collapsed — U+4E00-4E0F beats sixteen single values."""
    parts: list[str] = []
    run_start = run_end = codepoints[0]
    for cp in codepoints[1:]:
        if cp == run_end + 1:
            run_end = cp
            continue
        parts.append(f"U+{run_start:X}" if run_start == run_end else f"U+{run_start:X}-{run_end:X}")
        run_start = run_end = cp
    parts.append(f"U+{run_start:X}" if run_start == run_end else f"U+{run_start:X}-{run_end:X}")
    return ", ".join(parts)


def write_css(out_dir: Path, written: list[tuple[Path, list[int]]]) -> None:
    faces = [
        f"""@font-face {{
  font-family: "{FAMILY}";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("./{out.name}") format("woff2");
  unicode-range: {unicode_range(used)};
}}"""
        for out, used in written
    ]
    (out_dir / "wenkai.css").write_text(f"{HEADER}\n" + "\n\n".join(faces) + "\n", encoding="utf8")
