"""Purpose: freeze a cross-language parity fixture for the embedding classifier — the same
vectors, scored once in Python (numpy, the training side) and once in TypeScript
(classifier.ts, the shipping side), so a drift in either is a failing test rather than a
silently different profile.

The texts are written by hand here, not sampled from the training corpus: those are scraped
video titles that stay in the feed-mode repo (see train_classifiers.py). They cover the
taxonomy broadly plus the inputs that break things — empty, whitespace, punctuation only,
emoji, mixed scripts, and one text far longer than any real title.

The vectors are stored as base64 float32 rather than decimal text so both sides multiply the
exact same numbers; the only difference left to measure is the arithmetic.

Usage: python3 scripts/interest-model/make_parity_fixture.py
The JSON is written compact; run `npx biome check --write` on it afterwards so `pnpm lint`
stays green.
Main exports: none (script).
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from e5_encoder import E5Encoder  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(REPO, "packages/feature-browsing-interest/src")
DEFAULT_COEFFICIENTS = os.path.join(SRC, "classifierCoefficients.json")
DEFAULT_OUT = os.path.join(SRC, "classifierParity.json")
MAX_CHARS = 2000  # MAX_CLASSIFY_CHARS in classifier.ts / MAX_TEXT_CHARS in embeddings.rs

TEXTS = [
    "从零开始学 Rust：所有权与借用讲清楚",
    "大模型微调实战，用一块消费级显卡跑通",
    "新款轻薄本拆机评测，散热到底行不行",
    "国产芯片产业链最新进展汇总",
    "为什么天空是蓝色的？三分钟讲明白瑞利散射",
    "线性代数为什么要学特征值，一个例子说透",
    "宋朝人的一天是怎么过的",
    "心理学里的锚定效应，你每天都在中招",
    "日语五十音三天记住的方法",
    "期末周高效复习计划，我是这样安排的",
    "程序员面试八股文还有必要背吗",
    "美联储降息对普通人意味着什么",
    "小县城开一家咖啡店的真实账本",
    "这款独立游戏我通宵打了三遍",
    "英雄联盟季后赛最后一波团战复盘",
    "手游抽卡保底机制的数学原理",
    "开放世界游戏为什么越做越空洞",
    "本季度最值得追的新番盘点",
    "国产动画的工业化还差多远",
    "鬼畜区镇站之宝重制版",
    "虚拟主播的中之人到底重要吗",
    "十分钟讲完这部两小时的悬疑电影",
    "这部老电影的运镜今天看依然超前",
    "综艺里的剪辑套路，看完你就懂了",
    "一个人在家用吉他翻唱这首歌",
    "古典舞基本功训练日常记录",
    "三十块钱做一顿有肉有菜的晚饭",
    "租房改造，把出租屋变成想住的样子",
    "我的第一次独自旅行，云南七天",
    "健身两年身材变化对比，说点实话",
    "跑步膝盖疼，可能是这个动作错了",
    "凌晨四点的城市是什么样子",
    "毕业十年，我和同学们都去哪了",
    "养猫三年踩过的坑，新手必看",
    "田园生活第三十天，菜地丰收了",
    "汽车年检新规到底改了什么",
    "手工皮具制作全过程，耐心党福音",
    "科普：疫苗是怎么起作用的",
    "How transformers actually work, explained simply",
    "Learning Japanese with anime: does it really work?",
    "Rust vs Go：并发模型的取舍",
    "AI绘画🎨新手入门指南✨",
    "【纪录片】海底两万里的真实生物",
    "老师说这道题超纲了，其实一行就能解",
    "开箱！这个键盘手感绝了",
    "",
    "   ",
    "《》【】—— ……！？",
    "🐱🐶🐰🦊🐻",
    "深度学习" * 400,
]


def softmax(logits: np.ndarray) -> np.ndarray:
    shifted = logits - logits.max(axis=1, keepdims=True)
    exponentiated = np.exp(shifted)
    return exponentiated / exponentiated.sum(axis=1, keepdims=True)


def dequantise(head: dict) -> tuple[np.ndarray, np.ndarray]:
    weights = np.frombuffer(base64.b64decode(head["weightsBase64"]), dtype=np.int8)
    weights = weights.reshape(head["classes"], head["dims"]).astype(np.float32)
    scales = np.array(head["scales"], dtype=np.float32)[:, None]
    return weights * scales, np.array(head["intercepts"], dtype=np.float32)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--coefficients", default=DEFAULT_COEFFICIENTS)
    parser.add_argument("--model-dir", default=None)
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args()

    coefficients = json.load(open(args.coefficients, encoding="utf-8"))
    topic_w, topic_b = dequantise(coefficients["topic"])
    emotion_w, emotion_b = dequantise(coefficients["emotion"])
    valences = np.array(coefficients["emotionValences"], dtype=np.float32)

    encoder = E5Encoder(args.model_dir)
    vectors = encoder.encode([t[:MAX_CHARS] for t in TEXTS]).astype(np.float32)
    topics = softmax(vectors @ topic_w.T + topic_b)
    emotions = softmax(vectors @ emotion_w.T + emotion_b)

    rows = []
    for index, text in enumerate(TEXTS):
        rows.append(
            {
                "text": text,
                "vectorBase64": base64.b64encode(vectors[index].tobytes()).decode("ascii"),
                "topics": [round(float(p), 9) for p in topics[index]],
                "emotions": [round(float(p), 9) for p in emotions[index]],
                "topicTop1": int(topics[index].argmax()),
                "emotionTop1": int(emotions[index].argmax()),
                "valence": round(float(emotions[index] @ valences), 9),
            }
        )
    payload = {
        "note": "Generated by scripts/interest-model/make_parity_fixture.py. Texts are "
        "hand-written, not corpus samples. Vectors are float32 little-endian, base64.",
        "model": coefficients["model"],
        "prefix": coefficients["prefix"],
        "dims": int(vectors.shape[1]),
        "rows": rows,
    }
    with open(args.out, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, separators=(",", ":"))
        handle.write("\n")
    print(f"wrote {args.out} ({os.path.getsize(args.out) / 1024:.1f} KB, {len(rows)} rows)")
    print("now run: npx biome check --write " + args.out)


if __name__ == "__main__":
    main()
